port: 7890
socks-port: 7891
#redir-port: 7892
mixed-port: 7893
#tproxy-port: 7895
mode: global
log-level: info
allow-lan: true
external-controller: 0.0.0.0:9090
secret : ""
bind-address: "*"
external-ui: yacd-gh-pages
dns:
  enable: true
  ipv6: false
  enhanced-mode: redir-host
  listen: 127.0.0.1:7894
  use-hosts: true
  nameserver:
    - https://cloudflare-dns.com/dns-query
    - tls://1dot1dot1dot1.cloudflare-dns.com
  fallback:
    - https://dns.google/dns-query


proxies:
  - name: sshinjector-real8oiiu
    server: cdn.onlymega.com
    port: 443
    type: vmess
    uuid: eca50aa4-c027-4b57-9843-e3150fd791fd
    alterId: 0
    cipher: auto
    tls: true
    skip-cert-verify: true
    servername: idv3.xserv.cc
    network: ws
    ws-opts:
      path: /v2ray
      headers:
        Host: idv3.xserv.cc
    udp: true
proxy-groups:
  - name: FASTSSH-SSHKIT-HOWDY
    type: select
    proxies:
      - sshinjector-real8oiiu
      - DIRECT
rules:
  - MATCH,FASTSSH-SSHKIT-HOWDY
